#ifndef BALL_POSITION_ACTION_CONFIG_H
#define BALL_POSITION_ACTION_CONFIG_H

#include <stdint.h>

#define BALL_POSITION_DEFAULT_TOLERANCE_PX          ((int32_t)30)
#define BALL_POSITION_DEFAULT_SETTLE_SPEED_PX       ((int32_t)2)
#define BALL_POSITION_DEFAULT_STABLE_FRAMES         ((uint8_t)3U)
#define BALL_POSITION_DEFAULT_VISION_TIMEOUT_MS     ((uint32_t)500U)

#endif /* BALL_POSITION_ACTION_CONFIG_H */
