#ifndef BALL_POSITION_ACTION_CONFIG_H
#define BALL_POSITION_ACTION_CONFIG_H

#include <stdint.h>

#define BALL_POSITION_DEFAULT_TOLERANCE_MM          ((int32_t)7)
#define BALL_POSITION_DEFAULT_SETTLE_SPEED_MM_S     ((int32_t)15)
#define BALL_POSITION_DEFAULT_STABLE_FRAMES         ((uint8_t)3U)
#define BALL_POSITION_DEFAULT_VISION_TIMEOUT_MS     ((uint32_t)500U)

#define BALL_POSITION_CAPTURE_FRAMES                ((uint8_t)5U)
#define BALL_POSITION_CAPTURE_MIN_SCORE_MILLI       ((uint16_t)700U)
#define BALL_POSITION_CAPTURE_MAX_SPREAD_MM         ((int32_t)4)
#define BALL_POSITION_CAPTURE_MAX_SPEED_MM_S        ((int32_t)20)

#endif /* BALL_POSITION_ACTION_CONFIG_H */
